using System.Windows;
using System.Windows.Controls;
using SalesforceDebugAnalyzer.ViewModels;

namespace SalesforceDebugAnalyzer.Views.Tabs;

public partial class SummaryTab : UserControl
{
    public SummaryTab()
    {
        InitializeComponent();
    }

    private MainViewModel? ViewModel => DataContext as MainViewModel;

    private void CopySummary_Click(object sender, RoutedEventArgs e)
    {
        var vm = ViewModel;
        if (vm == null) return;

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("=== LOG ANALYSIS SUMMARY ===");
        if (!string.IsNullOrEmpty(vm.SummaryText))
            sb.AppendLine(vm.SummaryText);
        sb.AppendLine();

        if (vm.HasHealthData)
        {
            sb.AppendLine($"Health Score: {vm.HealthScore}/100 — {vm.HealthPlainStatement}");
            sb.AppendLine($"SOQL: {vm.SoqlStatusIcon}  DML: {vm.DmlStatusIcon}  CPU: {vm.CpuStatusIcon}  Errors: {vm.ErrorStatusIcon}");
            sb.AppendLine();
        }

        if (!string.IsNullOrEmpty(vm.FullSummaryText))
        {
            sb.AppendLine(vm.FullSummaryText);
            sb.AppendLine();
        }

        if (vm.CriticalIssues?.Count > 0)
        {
            sb.AppendLine("CRITICAL ISSUES:");
            foreach (var issue in vm.CriticalIssues.Take(3))
            {
                sb.AppendLine($"  • {issue.Title}");
                if (!string.IsNullOrEmpty(issue.Fix))
                    sb.AppendLine($"    Fix: {issue.Fix}");
            }
            sb.AppendLine();
        }

        if (vm.HighPriorityIssues?.Count > 0)
        {
            sb.AppendLine("HIGH PRIORITY:");
            foreach (var issue in vm.HighPriorityIssues.Take(3))
            {
                sb.AppendLine($"  • {issue.Title}");
                if (!string.IsNullOrEmpty(issue.Fix))
                    sb.AppendLine($"    Fix: {issue.Fix}");
            }
            sb.AppendLine();
        }

        sb.AppendLine("Generated by Black Widow Log Analyzer");

        var text = sb.ToString().Trim();
        if (!string.IsNullOrEmpty(text))
        {
            Clipboard.SetText(text);
            ShowCopyFeedback(sender as Button);
        }
    }

    private void CopyIssues_Click(object sender, RoutedEventArgs e)
    {
        var vm = ViewModel;
        if (vm?.SelectedLog?.Issues is { Count: > 0 } issues)
            Clipboard.SetText(string.Join("\n", issues));
    }

    private void CopyRecommendations_Click(object sender, RoutedEventArgs e)
    {
        var vm = ViewModel;
        if (vm?.SelectedLog?.Recommendations is { Count: > 0 } recs)
            Clipboard.SetText(string.Join("\n", recs));
    }

    private async void ShowCopyFeedback(Button? button)
    {
        if (button == null) return;

        var originalContent = button.Content;
        button.Content = "✓ Copied!";
        button.Background = new System.Windows.Media.SolidColorBrush(
            System.Windows.Media.Color.FromRgb(0x3B, 0xA5, 0x5D));

        try
        {
            await Task.Delay(1500);
            button.Content = originalContent;
            button.Background = new System.Windows.Media.SolidColorBrush(
                System.Windows.Media.Color.FromRgb(0x4E, 0x50, 0x58));
        }
        catch (TaskCanceledException) { }
        catch (InvalidOperationException) { }
    }
}
